### ISSUE TITLE
Menambahkan Readiness Probe Health Check via HTTP

### ISSUE THREAD

**Issue by yohang88** [sapawarga/video-service#43]
https://github.com/sapawarga/video-service/blob/5403258fa3e80ad5d7beb268c23fa401e466e98e/endpoint/endpoint.go#L134-L141

Nice catch @setiadijoe bikin health check 🚀  💪

Di teknologi container, health check ini memang jadi standar. Di Kubernetes, ada yang namanya Liveness dan Readiness probe. 

Bisa dibaca-baca: 
- https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes 
- https://medium.com/swlh/implement-health-checks-for-kubernetes-in-your-application-951eb483a05c

Yang sekarang udah ada ini nampaknya baru endpoint untuk liveness probe ya? Apakah bisa ditambahkan fungsional untuk readiness probe juga? Tujuannya agar bisa cek koneksi ke DB juga 😁  

Sehingga usulan saya dibuat 2 endpoint:

```
/health/live
/health/ready
```

Open for discussion yesss 😁

**Comment by setiadijoe** [comment]
btw bisa discuss di PR nya ya
